version: '3.4'
services:
  ui:
    build: 
      context: WebApp/ClientApp.
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:80
    depends_on:
      - webapi
      - db
  webapi:
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: 'mcr.microsoft.com/mssql/server:2017-latest'
    environment:
      MSSQP_SA_PASSWORD: 'Test12341234'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'